pre-install:
    windows: []
    linux: []

post-install:
    windows: []
    linux:
        # Link tmux config
        - "ln -s tmux.conf ~/.tmux.conf"

dependencies:
    windows: []
    arch: [tmux]
    debian: [tmux]

