pre-install: null

post-install:
    windows: null
    linux:
        # Download and install oh-my-zsh
        - "sh -c \"$(curl -fsSL https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh)\""
        # Update and relink
        - "./update_oh_my_zsh.sh"
        # Install fzf
        - "git clone --depth 1 https://github.com/junegunn/fzf.git ~/.fzf"
        - "~/.fzf/install"

dependencies:
    windows: null
    arch: [zsh, screenfetch, curl]
    debian: [zsh, screenfetch, curl]
